app/php_laravel/detail_user/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserLoginController;
use App\Http\Controllers\BiodataController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

});

Route::get('/login', function () {
	return view('before_login.login', ['title'=>'Login']);
})->name('login');

Route::get('/register', function () {
	return view('before_login.register', ['title'=>'Daftar']);
})->name('register');

Route::post('proclogin', function () {
	return view('before_login.register', ['title'=>'Daftar']);
})->name('tologin');

Route::resource('home', '\App\Http\Controllers\HomeController');
Route::resource('ulo', '\App\Http\Controllers\UserLoginController');
Route::resource('bio', '\App\Http\Controllers\BiodataController');

app/php_laravel/detail_user/resources/views/before_login/login.blade.php
@inject('fun', 'App\MyLibs\myfunction')
@extends('index')
@section('content')
@if( !isset($_COOKIE['login']) && !isset($_COOKIE['username']) && !isset($_COOKIE['email']) )
<div class="container m-t-10p borad-20">
    <div class="m-t-30 m-b-10 login">
        <h1 class="bold center">Login</h1>

        <div class="m-t-50">
            <form action="{{ route('ulo.store') }}" method="post">
                {{ csrf_field() }}
                {{ method_field('POST') }}
                <input type="hidden" name="type" id="type" value="{{ $fun->enval('login') }}" />

                <div class="form-group">
                    <input type="text" name="usermail" id="usermail" class="form-control" placeholder="Username / Email.." required />
                </div>

                <div class="form-group">
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password.." required />
                </div>

                <div class="center">
                    <button type="submit" class="btn btn-primary center">Masuk</button>
                </div>

                @if( isset($message) )
                    <div class="center m-t-50 m-b-10">
                        <h4 class="bold">{{ $message }}</h4>
                    </div>
                @endif

                <div class="down-10p m-r-10">
                    <div class="right">
                        <a href="{{ route('register') }}" class="bold">Daftar</a>
                        <?php
                        /*
                        <br/>
                        <a href="<?php echo '?'.$lib->setIDParam('pg', 'lupapassword'); ?>" class="">Lupa Password</a>
                        */
                        ?>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

<div class="container bottom">
    <div class="center copyright bold">
        Copyright © Syahri Ramadhan Wiraasmara
    </div>
</div>
@else
    <script>window.location.href = "../public/bio"; </script>
@endif
@endsection

app/php_laravel/detail_user/resources/views/before_login/lupapassword.blade.php
@inject('fun', 'App\MyLibs\myfunction')
@extends('index')
@section('content')
@if(!isset($_COOKIE[$fun->enid('login')]) && !isset($_COOKIE[$fun->enid('username')]))
<div class="container m-t-10p borad-20">
    <div class="m-t-30 m-b-10">
        <h1 class="bold center">Lupa Password</h1>

        <div class="m-t-50">
            <div class="bold italic underline m-b-20">Fitur ini belum berfungsi</div>
            <form action="<?php echo $path101->proc("login"); ?>" method="post">
                <input type="hidden" name="<?php echo $lib->tokenName("@Syslog:token"); ?>" id="<?php echo $lib->tokenName("@Syslog:token"); ?>"   value="<?php echo $lib->tokenValue(); ?>" />
                <input type="hidden" name="<?php echo $lib->tokenName("@Process:"); ?>"     id="<?php echo $lib->tokenName("@Process:"); ?>"       value="<?php echo $lib->tokenValue(); ?>" />
                <input type="hidden" name="<?php echo $lib->enlink("procont1"); ?>"         id="<?php echo $lib->enlink("procont1"); ?>"           value="<?php echo $lib->enval('as101'); ?>" />

                <div class="form-group">
                    <input type="text" name="<?php echo $lib->enlink('email'); ?>" id="<?php echo $lib->enlink('email'); ?>" class="form-control" placeholder="Email.." required />
                </div>

                <div class="center">
                    <a href="<?php echo '?'.$lib->setID ?>" class="btn btn-primary m-r-10">Batal</a>

                    <button type="submit" class="btn btn-primary m-l-10">OK</button>
                </div>

            </form>
        </div>

    </div>
</div>

app/php_laravel/detail_user/resources/views/before_login/register.blade.php
@inject('fun', 'App\MyLibs\myfunction')
@extends('index')
@section('content')
@if(!isset($_COOKIE[$fun->enlink('login')]) && !isset($_COOKIE[$fun->enlink('username')]))
<div class="container m-t-10p borad-20">
    <div class="m-t-30 m-b-10">
        <h1 class="bold center">Daftar Baru</h1>

        <div class="m-t-50">
            <form action="{{ route('ulo.store') }}" method="post">
                {{ csrf_field() }}
				{{ method_field('POST') }}
                <input type="hidden" name="type" id="type" value="{{ $fun->enval('register') }}" />

                <div class="form-group">
                    <input type="text" name="username" id="username" class="form-control" placeholder="Username.." required />
                </div>

                <div class="form-group">
                    <input type="text" name="email" id="email" class="form-control" placeholder="Email.." required />
                </div>

                <div class="form-group">
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password.." required />
                </div>

                <div class="form-group">
                    <input type="password" name="passver" id="passver" class="form-control" placeholder="Verifikasi Password.." required />
                </div>

                <div class="center">
                    <a href="{{ route('login') }}" class="btn btn-primary m-r-10">Batal</a>

                    <button type="submit" id="daftar" class="btn btn-primary m-l-10">Daftar</button>
                </div>

            </form>

            @if( isset($message) )
                <div class="center m-t-50 m-b-10">
                    <h4 class="bold">{{ $message }}</h4>
                </div>
            @endif

        </div>

    </div>
</div>

<script>
    $("<?php echo '#'.$fun->enlink('passver'); ?>").keyup(function(){

        var pass1 = $("<?php echo '#'.$fun->enlink('password'); ?>").val();
        var pass2 = $("<?php echo '#'.$fun->enlink('passver'); ?>").val();

        if(pass1 == pass2) {
            $("<?php echo '#'.$fun->enlink('daftar'); ?>").attr("disabled", false);
        }
        else {
            $("<?php echo '#'.$fun->enlink('daftar'); ?>").attr("disabled", true);
        }

    });

    $("<?php echo '#'.$fun->enlink('passver'); ?>").keydown(function(){

        var pass1 = $("<?php echo '#'.$fun->enlink('password'); ?>").val();
        var pass2 = $("<?php echo '#'.$fun->enlink('passver'); ?>").val();

        if(pass1 == pass2) {
            $("<?php echo '#'.$fun->enlink('daftar'); ?>").attr("disabled", false);
        }
        else {
            $("<?php echo '#'.$fun->enlink('daftar'); ?>").attr("disabled", true);
        }

    });
</script>
@else
    @php header("location: route('bio')"); @endphp
    <script>//window.location.href = "../bio"; </script>
@endif
@endsection