app/php_laravel/detail_user/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserLoginController;
use App\Http\Controllers\BiodataController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

});

Route::get('/login', function () {
	return view('before_login.login', ['title'=>'Login']);
})->name('login');

Route::get('/register', function () {
	return view('before_login.register', ['title'=>'Daftar']);
})->name('register');

Route::post('proclogin', function () {
	return view('before_login.register', ['title'=>'Daftar']);
})->name('tologin');

Route::resource('home', '\App\Http\Controllers\HomeController');
Route::resource('ulo', '\App\Http\Controllers\UserLoginController');
Route::resource('bio', '\App\Http\Controllers\BiodataController');

app/php_laravel/detail_user/resources/views/after_login/my102/biodata.blade.php
@inject('fun', 'App\MyLibs\myfunction')
@extends('index')
@section('content')
@if( isset($_COOKIE['login']) && isset($_COOKIE['username']) && isset($_COOKIE['email']) )
<div class="panel m-t-10">
    <h2 class="bold center">SELAMAT DATANG<br/>{{ $fun->readable($nama) }}</h2>

    <div class="m-t-30">
        <table class="table table-responsive width-100">
            <thead>
                <tr>
                    <th class="center">#</th>
                    <th class="center">Nama</th>
                    <th class="center">Email</th>
                    <th class="center">Tanggal Lahir</th>
                    <th class="center">Alamat</th>
                    <th class="center">Nomor Telepon</th>
                    <th class="center">Status</th>
                    <th class="center" colspan="2">--</th>
                </tr>
            </thead>

            <tbody>
                @php $nomor = 1; @endphp
                @foreach($biodata as $bio)
                    <tr>
                        <td>{{ $nomor; }}</td>
                        <td>{{ $fun->readable($bio->nama) }}</td>
                        <td>{{ $fun->readable($bio->email) }}</td>
                        <td>{{ $fun->readable($bio->tgl_lahir) }}</td>
                        <td>{{ $fun->readable($bio->alamat) }}</td>
                        <td>{{ $fun->readable($bio->tlp) }}</td>
                        <td>{{ $fun->readable($bio->status) }}</td>

                        <form action="{{ route('bio.destroy', $fun->readable($fun->enval($bio->id_102))) }}" method="post" id="{{ 'formdel'.$nomor }}">
                            {{ csrf_field() }}
                            @method('DELETE')
                            <td class="center">
                                <a href="{{ route('bio.edit', $fun->readable($fun->enval($bio->id_102))); }}">Edit</a>
                            </td>
                            <td class="center">
                                <button type="button" class="unbutton" id="{{ 'del'.$nomor; }}">Delete</button>
                            </td>
                        </form>
                        <script>
                            $("{{ '#del'.$nomor; }}").click(function(){
                                var cfm = confirm('Anda yakin ingin menghapus data ini?');
                                if(cfm == true) {
                                    $("{{ '#formdel'.$nomor; }}").submit();
                                }
                            });
                        </script>
                    </tr>
                    @php $nomor++; @endphp
                @endforeach
            </tbody>
        </table>

    </div>
</div>

<div class="panel menubottom">
    <div class="row">
        <div class="col-12 col-xs-12 col-md-12 col-lg-12 col-xl-12 m-b-10 center">
            <a href="bio/create"><i class="ion-android-add"></i></a>
        </div>
        <div class="col-4 col-xs-4 col-md-4 col-lg-4 col-xl-4 center">
            <a href="ulo"><i class="ion-android-person"></i></></a>
        </div>

        <div class="col-4 col-xs-4 col-md-4 col-lg-4 col-xl-4 center">
            <a href="bio"><i class="ion-android-home"></i></></a>
        </div>

        <div class="col-4 col-xs-4 col-md-4 col-lg-4 col-xl-4 center">
            <form action="{{ route('ulo.destroy', $fun->enval(0)) }}" method="post">
                {{ csrf_field() }}
                @method('DELETE')
                <input type="hidden" name="type" id="type" value="{{ $fun->enval('logout') }}" />
                <button type="submit" name="ok" id="ok" class="unbutton"><i class="ion-log-out"></i></button>
            </form>
        </div>

        <div class="col-12 col-xs-12 col-md-12 col-lg-12 col-xl-12 center">
            <span class="bold center">Copyright © Syahri Ramadhan Wiraasmara</span>
        </div>
    </div>
</div>
@else
    <script>window.location.href = "../public/login"; </script>
@endif
@endsection

app/php_laravel/detail_user/resources/views/after_login/my102/nebiodata.blade.php
@inject('fun', 'App\MyLibs\myfunction')
@extends('index')
@section('content')
@if( isset($_COOKIE['login']) && isset($_COOKIE['username']) && isset($_COOKIE['email']) )
    @php
    if($ne == 'edit') {
        $url        = route('bio.update', $fun->readable($fun->enval($biodata[0]->id_102)));

        $nama       = $fun->readable($biodata[0]['nama']);
        $email      = $fun->readable($biodata[0]['email']);
        $tgl        = $fun->readable($biodata[0]['tgl_lahir']);
        $alamat     = $fun->readable($biodata[0]['alamat']);
        $tlp        = $fun->readable($biodata[0]['tlp']);
        $status     = $fun->readable($biodata[0]['status']);

        $readonly   = "readonly";
        $route      = "../../bio";
    }
    else {
        $url        = route('bio.store');

        $nama       = null;
        $email      = null;
        $tgl        = date('Y-m-d');
        $alamat     = null;
        $tlp        = null;
        $status     = null;

        $readonly   = "";
        $route      = "../bio";
    }
    @endphp
    <div class="panel">
        <h2 class="bold center"><?php echo $title; ?></h2>

        <div class="m-t-30">
            <form action="{{ $url }}" method="post">
                {{ csrf_field() }}
                @if($ne == 'edit')
                {{ method_field('PATCH') }}
                @endif

                <div class="form-group">
                    <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama.." value="{{ $nama }}" required />
                </div>

                <div class="form-group">
                    <input type="email" name="email" id="email" class="form-control" placeholder="Email.." value="{{ $email }}" required {{ $readonly }} />
                </div>

                <div class="form-group">
                    <input type="date" name="tgl_lahir" id="tgl_lahir" class="form-control" placeholder="Tanggal Lahir.." value="{{ $tgl }}" />
                </div>

                <div class="form-group">
                    <input type="text" name="alamat" id="alamat" class="form-control" placeholder="Alamat.." value="{{ $alamat }}" />
                </div>

                <div class="form-group">
                    <input type="tel" name="tlp" id="tlp" class="form-control" placeholder="Nomor Telepon.." value="{{ $tlp }}" />
                </div>

                <div class="form-group">
                    <input type="text" name="status" id="status" class="form-control" placeholder="Status.." value="{{ $status }}" />
                </div>

                <div class="center">
                    <button type="submit" class="btn btn-primary center m-r-10">OK</button>
                    <a href="{{ $route }}" class="btn btn-primary center m-l-10">Batal</a>
                </div>
            </form>
        </div>
    </div>
@else
    <script>window.location.href = "../public/login"; </script>
@endif
@endsection